version: '3.9'

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/28

volumes:
  db_data:

services:
  web:
    image: nginx:alpine
    container_name: web_server
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      custom_net:
        ipv4_address: 10.10.10.2
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db_server
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql
    networks:
      custom_net:
        ipv4_address: 10.10.10.3
        aliases:
          - new_db
          - dev_db

